In [1]:
import numpy

In [2]:
my_list = [2,4,6,8]
output = my_list/2
output

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [4]:
my_list = numpy.array([2,4,6,8])
output = my_list/2
print(output)

[1. 2. 3. 4.]


In [6]:
my_two_dimension_array = numpy.array([[2,4,6,8],[3,6,9,12]])
my_two_dimension_array

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [7]:
my_two_dimension_array.ndim

2

In [8]:
multi_dimension_array = numpy.array([[[2,4,6,8],[3,6,9,12]],[[1,2,3,4],[2,4,6,8]]])
multi_dimension_array

array([[[ 2,  4,  6,  8],
        [ 3,  6,  9, 12]],

       [[ 1,  2,  3,  4],
        [ 2,  4,  6,  8]]])

In [10]:
multi_dimension_array.ndim

3

In [11]:
array_with_zeros = numpy.zeros((2,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
array_with_ones = numpy.ones((2,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
data_with_range = numpy.arange(20)
data_with_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
data_with_range = numpy.arange(2,20)
data_with_range

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [15]:
data_with_range = numpy.arange(0,20,2)
data_with_range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
data_with_line_space = numpy.linspace(0,1,5)
data_with_line_space

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
data_with_line_space = numpy.linspace(0,10,5)
data_with_line_space

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
empty_array = numpy.empty((2,3))
empty_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
array_with_zeros = numpy.zeros((2,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
empty_array = numpy.empty((2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
multi_dimension_array = numpy.array([[[2,4,6,8],[3,6,9,12]],[[1,2,3,4],[2,4,6,8]]])
multi_dimension_array

array([[[ 2,  4,  6,  8],
        [ 3,  6,  9, 12]],

       [[ 1,  2,  3,  4],
        [ 2,  4,  6,  8]]])

In [26]:
empty_array = numpy.empty((2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
my_two_dimension_array = numpy.array([[2,4,6,8],[3,6,9,12]])
my_two_dimension_array

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [31]:
my_two_dimension_array[1]

array([ 3,  6,  9, 12])

In [32]:
my_two_dimension_array[0:1]

array([[2, 4, 6, 8]])

In [34]:
my_two_dimension_array[:,0:2]

array([[2, 4],
       [3, 6]])

In [35]:
my_new_array = my_two_dimension_array
my_new_array

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [36]:
my_new_array[0] = 100
my_new_array

array([[100, 100, 100, 100],
       [  3,   6,   9,  12]])

In [37]:
my_two_dimension_array

array([[100, 100, 100, 100],
       [  3,   6,   9,  12]])

In [38]:
deep_copy_arrary = my_two_dimension_array.copy()
deep_copy_arrary

array([[100, 100, 100, 100],
       [  3,   6,   9,  12]])

In [39]:
my_two_dimension_array

array([[100, 100, 100, 100],
       [  3,   6,   9,  12]])

In [40]:
deep_copy_arrary[0] = 7
deep_copy_arrary

array([[ 7,  7,  7,  7],
       [ 3,  6,  9, 12]])

In [41]:
my_two_dimension_array

array([[100, 100, 100, 100],
       [  3,   6,   9,  12]])

In [42]:
a1 = numpy.array([2,4,6])
a2 = numpy.array([3,6,9])

addition = a1 + a2
addition

array([ 5, 10, 15])

In [43]:
a1 = numpy.array([2,4,6])
a2 = numpy.array([3,6,9])

subtraction = a1 - a2
subtraction

array([-1, -2, -3])

In [44]:
a1 = numpy.array([2,4,6])
a2 = numpy.array([3,6,9])

multiplication = a1 * a2
multiplication

array([ 6, 24, 54])

In [45]:
a1 = numpy.array([2,4])
a2 = numpy.array([3,6,9])

addition = a1 + a2
addition

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [49]:
a1 = numpy.array([2,4],dtype=numpy.float64)
a2 = numpy.array([3,6,9],dtype = numpy.float64)

max_len = max(len(a1),len(a2))
max_len

3

In [50]:
a1_padding = numpy.pad(a1,(0,max_len - len(a1)),constant_values = numpy.nan)
a2_padding = numpy.pad(a2,(0,max_len - len(a2)),constant_values = numpy.nan)

added_value = a1_padding + a2_padding
added_value

array([ 5., 10., nan])

In [52]:
a1_padding

array([ 2.,  4., nan])

In [53]:
a2_padding

array([3., 6., 9.])

In [55]:
my_array = numpy.array([2,4,6])
my_scaler_value = 2
output = my_array * my_scaler_value
output

array([ 4,  8, 12])

In [56]:
my_array = numpy.array([2,4,6])
my_array2 = numpy.array([[1,2,3],[10,20,30]])
my_array2.ndim

2

In [57]:
output = my_array + my_array2
output

array([[ 3,  6,  9],
       [12, 24, 36]])

In [58]:
my_array = numpy.array([2,4,6])
new = numpy.add(my_array,5)
new

array([ 7,  9, 11])

In [59]:
sq_root = numpy.sqrt(my_array)
sq_root

array([1.41421356, 2.        , 2.44948974])

In [60]:
exp_value = numpy.exp(my_array)
exp_value

array([  7.3890561 ,  54.59815003, 403.42879349])

In [62]:
a = numpy.array([1, 2, 3])
b = numpy.array([4, 5, 6])
output = a + b
output

array([5, 7, 9])

In [63]:
output = numpy.add(a,b)
output

array([5, 7, 9])

In [64]:
output = numpy.dot(a,b)
output

32

In [65]:
output = numpy.multiply(a,b)
output

array([ 4, 10, 18])

In [66]:
output = sum(output)
output

32

In [68]:
a = numpy.array([1, 2, 3])
b = numpy.array([4, 5, 6])
final = numpy.matmul(a,b)
final

32

In [71]:
a = numpy.array([[1,2],[10,15]])
b = numpy.array([[2,4],[5, 6]])
final = numpy.matmul(a,b)
final

array([[ 12,  16],
       [ 95, 130]])

In [73]:
a = numpy.array([[1, 2], [3, 4]])
transpose = numpy.transpose(a)
transpose

array([[1, 3],
       [2, 4]])

In [76]:
my_data = numpy.array([2,4,6,8,10,12])
ouput = my_data.reshape((3,2))
ouput

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [79]:
my_data = numpy.array([2,4,6,8,10,12,14,16])
my_data.resize((3,3))
my_data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16,  0]])

In [80]:
# Flattening a multi-dimensional array
arr_2d = numpy.array([[1, 2], [3, 4], [5, 6]])
flattened = arr_2d.flatten()
flattened




array([1, 2, 3, 4, 5, 6])

In [81]:

# Raveling a multi-dimensional array
raveled = arr_2d.ravel()
raveled

array([1, 2, 3, 4, 5, 6])

In [83]:
arr_2d = numpy.array([[1, 2], [3, 4], [5, 6]])
transpose_arr = arr_2d.T
transpose_arr

array([[1, 3, 5],
       [2, 4, 6]])

In [84]:
# Vertical stacking
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
stacked_v = np.vstack((arr1, arr2))
stacked_v


array([[1, 2],
       [3, 4]])

In [85]:
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
stacked_h = np.hstack((arr1, arr2))
stacked_h

array([1, 2, 3, 4])

In [86]:
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
stacked_d = np.dstack((arr1, arr2))
stacked_d

array([[[1, 3],
        [2, 4]]])

In [87]:
# Split an array into 3 parts
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)
split_arr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [92]:
arr = np.array([[1, 2, 3],[ 4, 5, 6]])
split_arr = np.hsplit(arr, 3)
split_arr

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [89]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.vsplit(arr, 3)
split_arr

ValueError: vsplit only works on arrays of 2 or more dimensions